version: '3'

services:
    tftp:
        build: tftp
        ports:
            - "0.0.0.0:69:69/udp"
        volumes:
            - tftp-data:/var/tftpboot:ro
        restart: unless-stopped

    pxeboot:
        image: alpine:3.14
        env_file: .env_pxeboot
        volumes:
            - ./pxeboot:/pxeboot:z
            - tftp-data:/tftpboot:z
        command: sh -c "rm -rf /tftpboot/* && /pxeboot/gen-pxeboot-cfg.sh && cp -rf /pxeboot/tmp/* /tftpboot/ && rm /tftpboot/*.zip"

volumes:
    tftp-data:
