version: '3'

services:
    tftp:
        build: tftp
        ports:
            - "69:69/udp"
        volumes:
            - tftp-data:/var/tftpboot:ro
        restart: unless-stopped

    pxeboot:
        image: alpine:latest
        env_file: .env_pxeboot
        volumes:
            - ./pxeboot:/pxeboot
            - tftp-data:/tftpboot
        command: sh -c "/pxeboot/gen-pxeboot-cfg.sh && cp -rf /pxeboot/tmp/* /tftpboot/"

volumes:
    tftp-data:
